# Generated by Django 4.0.5 on 2022-07-08 02:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login_info',
            old_name='Password',
            new_name='Full_Name',
        ),
        migrations.RemoveField(
            model_name='login_info',
            name='User_name',
        ),
        migrations.AddField(
            model_name='login_info',
            name='Email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
