# Generated by Django 4.0.5 on 2022-07-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0002_rename_password_login_info_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Key_value', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
