# Generated by Django 4.0.5 on 2022-07-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0003_key_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=100)),
                ('Password_value', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
