# Generated by Django 4.0.5 on 2022-07-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0004_admin_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_uploads_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_Name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
