# Generated by Django 4.0.5 on 2022-07-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0005_admin_uploads_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Serial_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
